# 1. Cáº¥u trÃºc cá»§a má»™t extention

# 1.1 Ná»n táº£n lÃ½ thuyáº¿t vá» Database vÃ  User Interface trong REVIT API
ThÃ´ng thÆ°á»ng thÃ¬ cÃ¡c API cá»§a Pyrevit sáº½ Ä‘Æ°á»£c náº±m á»Ÿ Autodesk.
<pre>
    import Autodek
    print(dir(Autodek))
    output: ['Revit']
</pre>
output: lÃ  1 danh sÃ¡ch bao gá»“m 1 pháº§n tá»­. Ná»›i Ä‘Ã¢y chá»©a táº¥t cáº£ cÃ¡c API Ä‘á»ƒ tÆ°Æ¡ng tÃ¡c vá»›i REVIT.

VÃ  trong Autodesk.Revit chá»©a cÃ¡c Class:
<pre>
    from Autodesk import Revit
    print(dir(Revit))
    output: ['ApplicationServices', 'Attributes', 'Creation', 'DB', 'Exceptions', 'UI']
</pre>

Giáº£i thÃ­ch vá» cÃ¡c class nÃ y: 
- tao 1 cÃ¡i báº£n
- cÃ³ 6 dÃ²ng vÃ  1 cá»™t
- giáº£i thÃ­ch cÃ¡c class nÃ y

VD:

| Cá»™t 1 | Cá»™t 2 | Cá»™t 3 |
|-------|--------|-------|
| HÃ ng 1 - A | HÃ ng 1 - B | HÃ ng 1 - C |
| HÃ ng 2 - A | HÃ ng 2 - B | HÃ ng 2 - C |



Document(doc): Ä‘Ã¢y lÃ  Ä‘á»‘i tÆ°á»£ng Ä‘áº¡i diá»‡n cho cÆ¡ sá»Ÿ dá»­ liá»‡u. NÃ³ chá»©a táº¥t cáº£ cÃ¡c Element(TÆ°á»ng, cá»­a, ...) cÃ¡c cÃ i Ä‘áº·t, thÃ´ng tin dá»± Ã¡n. Má»i thao tÃ¡c <b>truy váº¥n</b> vÃ  <b>lá»c</b> Ä‘á»u thÃ´ng qua Ä‘á»‘i tÆ°á»£ng nÃ y.

UIDocument(uidoc): Äáº¡i diá»‡n cho lá»›p giao diá»‡n ngÆ°á»i dÃ¹ng mÃ  chÃºng ta Ä‘ang tÆ°Æ¡ng tÃ¡c. NÃ³ quáº£n lÃ½ nhá»¯ng gÃ¬ mÃ  chÃºng ta tháº¥y trÃªn mÃ n hÃ¬nh, cá»­a sá»• vÃ  Ä‘áº·t biá»‡t lÃ  cÃ¡c hÃ nh Ä‘á»™ng lá»±a chá»n Ä‘á»‘i tÆ°á»£ng.


## Filtering

CÃ´ng cá»¥ chÃ­nh cho viá»‡c nÃ y lÃ  FilteredElementCollector. <br>
CÃ¡ch hoáº¡t Ä‘á»™ng: Báº¡n báº¯t Ä‘áº§u má»™t FilteredElementCollector, sau Ä‘Ã³ Ã¡p dá»¥ng cÃ¡c bá»™ lá»c (OfCategory, OfClass, WhereElementIsNotElementType, etc.) Ä‘á»ƒ thu háº¹p pháº¡m vi tÃ¬m kiáº¿m.
<pre>
    # Import cÃ¡c thÆ° viá»‡n cáº§n thiáº¿t
    from Autodesk.Revit.DB import FilteredElementCollector, BuiltInCategory, Wall

    # Láº¥y document hiá»‡n hÃ nh
    doc = __revit__.ActiveUIDocument.Document

    # Báº¯t Ä‘áº§u Collector, lá»c theo category lÃ  Walls vÃ  láº¥y vá» cÃ¡c element instances
    walls = FilteredElementCollector(doc).OfCategory(BuiltInCategory.OST_Walls).WhereElementIsNotElementType().ToElements()

    # In ra sá»‘ lÆ°á»£ng tÆ°á»ng tÃ¬m tháº¥y
    print("TÃ¬m tháº¥y {} bá»©c tÆ°á»ng.".format(len(walls)))

    for wall in walls:
        # wall bÃ¢y giá» lÃ  má»™t Ä‘á»‘i tÆ°á»£ng Wall, báº¡n cÃ³ thá»ƒ truy cáº­p thuá»™c tÃ­nh cá»§a nÃ³
        print("ID cá»§a tÆ°á»ng: {}".format(wall.Id))
</pre>



## Selection

ÄÃ¢y lÃ  cÃ¡ch Ä‘á»ƒ báº¡n tÆ°Æ¡ng tÃ¡c vá»›i nhá»¯ng gÃ¬ ngÆ°á»i dÃ¹ng Ä‘ang chá»n trá»±c tiáº¿p trÃªn giao diá»‡n Revit. <br>
CÃ¡ch hoáº¡t Ä‘á»™ng: Báº¡n truy cáº­p vÃ o UIDocument (giao diá»‡n ngÆ°á»i dÃ¹ng) Ä‘á»ƒ láº¥y táº­p há»£p cÃ¡c Ä‘á»‘i tÆ°á»£ng Ä‘ang Ä‘Æ°á»£c chá»n.
<pre>
    from Autodesk.Revit.DB import ElementId

    # Láº¥y uidoc (tÃ i liá»‡u giao diá»‡n ngÆ°á»i dÃ¹ng)
    uidoc = __revit__.ActiveUIDocument

    # Láº¥y táº­p há»£p cÃ¡c ID cá»§a element Ä‘ang Ä‘Æ°á»£c chá»n
    selected_ids = uidoc.Selection.GetElementIds()

    if not selected_ids:
        print("KhÃ´ng cÃ³ Ä‘á»‘i tÆ°á»£ng nÃ o Ä‘Æ°á»£c chá»n.")
    else:
        print("CÃ¡c Ä‘á»‘i tÆ°á»£ng Ä‘ang Ä‘Æ°á»£c chá»n:")
        for element_id in selected_ids:
            # Tá»« ID, ta cÃ³ thá»ƒ láº¥y vá» Ä‘á»‘i tÆ°á»£ng Element
            element = doc.GetElement(element_id)
            print("- ID: {}, Category: {}".format(element.Id, element.Category.Name))
</pre>

## Parameters

<pre>
    # Giáº£ sá»­ 'wall' lÃ  má»™t Ä‘á»‘i tÆ°á»£ng tÆ°á»ng Ä‘Ã£ Ä‘Æ°á»£c láº¥y tá»« trÆ°á»›c
    # (vÃ­ dá»¥: wall = walls[0] tá»« má»¥c Filtering)

    # Láº¥y parameter báº±ng tÃªn
    comment_param = wall.LookupParameter("Comments")

    if comment_param:
        # Äá»c giÃ¡ trá»‹ cÅ©
        old_comment = comment_param.AsString()
        print("Comment cÅ©: '{}'".format(old_comment))
        
        # Ghi giÃ¡ trá»‹ má»›i (pháº£i náº±m trong Transaction)
        # Xem má»¥c 7. Transactions
        from Autodesk.Revit.DB import Transaction
        
        t = Transaction(doc, "Thay Ä‘á»•i Comment cá»§a tÆ°á»ng")
        t.Start()
        
        comment_param.Set("ÄÃ¢y lÃ  comment má»›i tá»« script Python")
        
        t.Commit()
        
        print("ÄÃ£ cáº­p nháº­t comment thÃ nh cÃ´ng.")

</pre>

## Collections

ğŸ˜…ğŸ¤£â˜ºï¸


##  Views

<pre>

    from Autodesk.Revit.DB import Transaction

    # Láº¥y view Ä‘ang má»Ÿ
    active_view = doc.ActiveView

    print("TÃªn view hiá»‡n táº¡i: {}".format(active_view.Name))

    # Äá»•i tÃªn view
    t = Transaction(doc, "Äá»•i tÃªn View")
    t.Start()

    active_view.Name = active_view.Name + " - ÄÃ£ chá»‰nh sá»­a"

    t.Commit()

    print("ÄÃ£ Ä‘á»•i tÃªn view thÃ nh cÃ´ng.")

</pre>


## Transactions 

Transaction Ä‘áº£m báº£o tÃ­nh toÃ n váº¹n cá»§a cÆ¡ sá»Ÿ dá»¯ liá»‡u. NÃ³ cho phÃ©p Revit "gom" má»™t loáº¡t cÃ¡c thay Ä‘á»•i láº¡i thÃ nh má»™t hÃ nh Ä‘á»™ng duy nháº¥t. Náº¿u cÃ³ lá»—i xáº£y ra giá»¯a chá»«ng, toÃ n bá»™ cÃ¡c thay Ä‘á»•i trong transaction sáº½ Ä‘Æ°á»£c hoÃ n tÃ¡c (rollback), giá»¯ cho mÃ´ hÃ¬nh khÃ´ng bá»‹ há»ng. NÃ³ cÅ©ng lÃ  cÆ¡ cháº¿ Ä‘á»ƒ Revit cÃ³ thá»ƒ thá»±c hiá»‡n chá»©c nÄƒng Undo/Redo.